name: DUI
favicon: null
layout_spectrum: 0.16284386278130114
typography_spectrum: 0.07030670461244881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
